name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: actions/setup-go@v2


      with:
        go-version: '1.14.1'


    - name: Save commit SHA
      run: |
        mkdir -p ./pr
        echo $(git rev-parse --short "$GITHUB_SHA") > ./pr/SHA

    - name: Save REF number
      run: |
        echo ${GITHUB_REF#refs/heads/} > ./pr/REF

    - name: Create coverage report
      run: |
        go test ./... -coverprofile=./pr/c.out

    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/
