name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
    - uses: actions/setup-go@v2


      with:
        go-version: '1.14.1'


    - name: Save commit SHA
      run: |
        mkdir -p ./pr
        echo ${{ github.sha }} > ./pr/SHA

    - name: Save commit owner
      run: |
        echo ${{ github.repository_owner }} > ./pr/OWNER

    - name: Save REF number
      run: |
        echo $GITHUB_HEAD_REF > ./pr/REF

    - name: Save Repository
      run: |
        echo ${{ github.repository }} > ./pr/REPO

    - name: Create coverage report
      run: |
        go test ./... -coverprofile=./pr/c.out

    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: pr/
