name: Upload code coverage securely to Code Climate

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/pr.zip', Buffer.from(download.data));
      - run: unzip pr.zip
      - env:           
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
          GIT_COMMIT_SHA: $(cat ${{github.workspace}}/pr/SHA)
          GIT_BRANCH: $(cat ${{github.workspace}}/pr/REF)
          REPOSITORY: $(cat ${{github.workspace}}/pr/REPO)
          OWNER: $(cat ${{github.workspace}}/pr/OWNER)

      - name: 'Get and set commit time'
        uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const commit_details = await github.git.getCommit({owner: process.env.OWNER, repo: process.env.REPOSITORY, commit_sha: process.env.GIT_COMMIT_SHA});
            return commit_details.data.author.date
        env:
          COMMITTED_AT: ${{ steps.author-date.outputs.result }}
      - run: echo $COMMITTED_AT was time committed.
      
      - name: Upload to code climate
        uses: paambaati/codeclimate-action@v2.7.5
        env:

        with:
          prefix: github.com/${{ REPOSITORY }}
          debug: true
          coverageLocations: |
              ${{github.workspace}}/pr/c.out:gocov
